const filmNames = [
  '180',
  '24 Hours on Craigslist',
  'A Night Full of Rain',
  'Summertime',
  'About a Boy',
  'Age of Adaline',
  'After the Thin Man',
  'Ant-Man',
  'Americana',
  'Another 48 Hours',
  'Around the Fire',
  'Attack of the Killer Tomatoes',
  'Basic Instinct',
  'Bedazzled',
  'Blue Jasmine',
  'Bee Season',
  'Bicentennial Man',
  'Big Eyes',
  'Big Sur',
  'Boys and Girls',
  'Broken-A Modern Love Story ',
  'Cardinal X',
  'Casualties of War',
  'Class Action',
  'Common Threads: Stories From the Quilt',
  'Confessions of a Burning Man',
  'Copycat',
  'Dawn of the Planet of the Apes',
  'Desperate Measures',
  'Doctor Dolittle',
  'Getting Even with Dad',
  'Dopamine',
  'Dr. Dolittle 2',
  'Faces of Death',
  'Fandom',
  'Fat Man and Little Boy',
  'Final Analysis',
  'Flubber',
  'Forrest Gump',
  '40 Days and 40 Nights',
  'George of the Jungle',
  'God is a Communist?* (show me heart universe)',
  'Godzilla',
  'I Am Michael',
  'Haiku Tunnel',
  'Happy Gilmore',
  'Heart and Souls',
  'Just Like Heaven',
  'Hereafter',
  'High Crimes',
  'Homeward Bound II: Lost in San Francisco',
  'House of Sand and Fog',
  'How Stella Got Her Groove Back',
  'Hulk',
  'Pretty Woman',
  `I's`,
  'Steve Jobs',
  'James and the Giant Peach',
  'Julie and Jack',
  'Looking',
  'Metro',
  'Milk',
  'Need For Speed',
  'Night of Henna',
  'On the Road',
  'Pacific Heights',
  'Parks and Recreation',
  'Quitters',
  'Patch Adams',
  'Playing Mona Lisa',
  'Raising Cain',
  'Red Diaper Baby',
  'Red Widow',
  'Rent',
  'Rollerball',
  'Romeo Must Die',
  'San Andreas',
  'Sausalito',
  'Sense8',
  'Serendipity',
  'Seven Girlfriends',
  'Shattered',
  'Shoot the Moon',
  'Sister Act',
  'Sister Act 2: Back in the Habit',
  'Smile Again, Jenny Lee',
  'Sneakers',
  'So I Married an Axe Murderer',
  'Stigmata',
  'Sweet November',
  'Swing',
  'Terminator - Genisys',
  'The Assassination of Richard Nixon',
  'The Bachelor',
  'The Bridge',
  'The Californians',
  'The Candidate',
  'The Core',
  'The Diary of a Teenage Girl',
  'The Doctor',
  'The Doors',
  'The Internship',
  'The Other Sister',
  'The Parent Trap',
  'Vegas in Space',
  'The Princess Diaries',
  'The Pursuit of Happyness',
  'The Rock',
  'The Sweetest Thing',
  'The Wedding Planner',
  'The Woman In Red',
  'The Zodiac',
  'Twisted',
  'Under the Tuscan Sun',
  'Until the End of the World',
  'What Dreams May Come',
  'What the Bleep Do We Know',
  `What's Up Doc?`,
  'When a Man Loves a Woman',
  'Woman on Top',
  'Zodiac',
  'Murder in the First, Season 1',
  'Looking Season 2 ep 202',
  'Looking Season 2 ep 203',
  'Murder in the First, Season 2',
  'Looking Season 2 ep 209',
  'Looking Season 2 ep 205',
  'Looking Season 2 ep 204',
  'Looking \'Special\'',
  'Sense8 - Season 2',
  'Chance- Season 1 ep102',
  'Chance- Season 1 ep109',
  'Budding Prospects, Pilot',
  'Pushing Dead',
  'When We Rise',
  'Chance- Season 1 ep104',
  'Etruscan Smile',
  'Bar Rescue - Season 4 Ep 21',
  'Chance - Season 1 Pilot',
  'Looking Season 2 ep 206',
  'Birth of the Dragon',
  'GirlBoss',
  'Chance- Season 1 ep110',
  'Looking Season 2 ep 210',
  'Looking Season 2 ep 207',
  'Chance- Season 1 ep106',
  'Chance- Season 1 ep108',
  'Bar Rescue - Season 4 Ep 18',
  'Looking Season 2 ep 208',
  'Chance- Season 1 ep107',
  'Murder in the First, Season 3',
  'Chance- Season 1 ep103',
  'Chance - Season 1 ep105',
  'Chance - Season 1ep105',
  'Mission (aka City of Bars)',
  'Bar Rescue',
  'Nine Months',
  'Superman',
  'Time After Time',
  'Bullitt',
  'The Game',
  'Nine to Five',
  'Herbie Rides Again',
  'Edtv',
  'Memoirs of an Invisible Man',
  'The Organization',
  'The Caine Mutiny',
  'Interview With The Vampire',
  'Pal Joey',
  'Invasion of the Body Snatchers',
  'The Net',
  'Cherish',
  'D.O.A',
  'The Graduate',
  'Freebie and the Bean',
  'The Right Stuff',
  'The Enforcer',
  'Tin Cup',
  'Never Die Twice',
  'Alcatraz',
  'The Dead Pool',
  'Jagged Edge',
  'Innerspace',
  'Dirty Harry',
  'Sudden Impact',
  'Sudden Fear',
];
export default filmNames;
